Dec 07 05:10:04 cloud-init[2436]: util.py[DEBUG]: Cloud-init v. 0.7.6 running 'init-local' at Mon, 07 Dec 2020 05:10:04 +0000. Up 6.07 seconds.
Dec 07 05:10:04 cloud-init[2436]: util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytes
Dec 07 05:10:04 cloud-init[2436]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance/boot-finished
Dec 07 05:10:04 cloud-init[2436]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
Dec 07 05:10:04 cloud-init[2436]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/data/no-net
Dec 07 05:10:04 cloud-init[2436]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
Dec 07 05:10:04 cloud-init[2436]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Dec 07 05:10:04 cloud-init[2436]: __init__.py[DEBUG]: Looking for for data source in: ['Ec2', 'None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM']
Dec 07 05:10:04 cloud-init[2436]: __init__.py[DEBUG]: Searching for data source in: []
Dec 07 05:10:04 cloud-init[2436]: cloud-init[DEBUG]: No local datasource found
Dec 07 05:10:04 cloud-init[2436]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
Dec 07 05:10:04 cloud-init[2436]: util.py[DEBUG]: Read 10 bytes from /proc/uptime
Dec 07 05:10:04 cloud-init[2436]: util.py[DEBUG]: cloud-init mode 'init' took 0.050 seconds (0.05)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Cloud-init v. 0.7.6 running 'init' at Mon, 07 Dec 2020 05:10:04 +0000. Up 6.25 seconds.
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytes
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Running command ['ifconfig', '-a'] with allowed return codes [0] (shell=False, capture=True)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Running command ['netstat', '-rn'] with allowed return codes [0] (shell=False, capture=True)
Dec 07 05:10:04 cloud-init[2442]: cloud-init[DEBUG]: Checking to see if files that we need already exist from a previous run that would allow us to stop early.
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Reading from /var/lib/cloud/data/no-net (quiet=False)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
Dec 07 05:10:04 cloud-init[2442]: cloud-init[DEBUG]: Execution continuing, no previous run detected that would allow us to stop early.
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
Dec 07 05:10:04 cloud-init[2442]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Dec 07 05:10:04 cloud-init[2442]: __init__.py[DEBUG]: Looking for for data source in: ['Ec2', 'None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM', 'NETWORK']
Dec 07 05:10:04 cloud-init[2442]: __init__.py[DEBUG]: Searching for data source in: ['DataSourceEc2', 'DataSourceNone']
Dec 07 05:10:04 cloud-init[2442]: __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceEc2.DataSourceEc2'>
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Reading from /var/lib/cloud/seed/ec2/meta-data (quiet=False)
Dec 07 05:10:04 cloud-init[2442]: DataSourceEc2.py[DEBUG]: Removed the following from metadata urls: ['http://instance-data.:8773']
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/1] open 'http://169.254.X.X/latest/meta-data/instance-id' with {'url': 'http://169.254.X.X/latest/meta-data/instance-id', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 50.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/instance-id (200, 19b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: DataSourceEc2.py[DEBUG]: Using metadata source: 'http://169.254.X.X'
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/user-data' with {'url': 'http://169.254.X.X/latest/user-data', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/user-data (200, 397b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/' with {'url': 'http://169.254.X.X/latest/meta-data/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/ (200, 290b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/block-device-mapping/' with {'url': 'http://169.254.X.X/latest/meta-data/block-device-mapping/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/block-device-mapping/ (200, 8b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/block-device-mapping/ami' with {'url': 'http://169.254.X.X/latest/meta-data/block-device-mapping/ami', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/block-device-mapping/ami (200, 9b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/block-device-mapping/root' with {'url': 'http://169.254.X.X/latest/meta-data/block-device-mapping/root', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/block-device-mapping/root (200, 9b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/events/' with {'url': 'http://169.254.X.X/latest/meta-data/events/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/events/ (200, 12b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/events/maintenance/' with {'url': 'http://169.254.X.X/latest/meta-data/events/maintenance/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/events/maintenance/ (200, 17b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/events/maintenance/scheduled' with {'url': 'http://169.254.X.X/latest/meta-data/events/maintenance/scheduled', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/events/maintenance/scheduled (200, 2b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/events/maintenance/history' with {'url': 'http://169.254.X.X/latest/meta-data/events/maintenance/history', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/events/maintenance/history (200, 2b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/iam/' with {'url': 'http://169.254.X.X/latest/meta-data/iam/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/iam/ (200, 26b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/iam/info' with {'url': 'http://169.254.X.X/latest/meta-data/iam/info', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/iam/info (200, 291b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/identity-credentials/' with {'url': 'http://169.254.X.X/latest/meta-data/identity-credentials/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/identity-credentials/ (200, 4b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/identity-credentials/ec2/' with {'url': 'http://169.254.X.X/latest/meta-data/identity-credentials/ec2/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/identity-credentials/ec2/ (200, 26b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/identity-credentials/ec2/info' with {'url': 'http://169.254.X.X/latest/meta-data/identity-credentials/ec2/info', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/identity-credentials/ec2/info (200, 98b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/metrics/' with {'url': 'http://169.254.X.X/latest/meta-data/metrics/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/metrics/ (200, 7b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/metrics/vhostmd' with {'url': 'http://169.254.X.X/latest/meta-data/metrics/vhostmd', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/metrics/vhostmd (200, 38b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/network/' with {'url': 'http://169.254.X.X/latest/meta-data/network/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/network/ (200, 11b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/network/interfaces/' with {'url': 'http://169.254.X.X/latest/meta-data/network/interfaces/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/network/interfaces/ (200, 5b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/network/interfaces/macs/' with {'url': 'http://169.254.X.X/latest/meta-data/network/interfaces/macs/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/network/interfaces/macs/ (200, 18b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/network/interfaces/macs/02:ec:5f:e8:eb:70/' with {'url': 'http://169.254.X.X/latest/meta-data/network/interfaces/macs/02:ec:5f:e8:eb:70/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/network/interfaces/macs/02:ec:5f:e8:eb:70/ (200, 182b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/network/interfaces/macs/02:ec:5f:e8:eb:70/local-hostname' with {'url': 'http://169.254.X.X/latest/meta-data/network/interfaces/macs/02:ec:5f:e8:eb:70/local-hostname', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/network/interfaces/macs/02:ec:5f:e8:eb:70/local-hostname (200, 43b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/network/interfaces/macs/02:ec:5f:e8:eb:70/security-groups' with {'url': 'http://169.254.X.X/latest/meta-data/network/interfaces/macs/02:ec:5f:e8:eb:70/security-groups', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/network/interfaces/macs/02:ec:5f:e8:eb:70/security-groups (200, 105b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/network/interfaces/macs/02:ec:5f:e8:eb:70/vpc-ipv4-cidr-blocks' with {'url': 'http://169.254.X.X/latest/meta-data/network/interfaces/macs/02:ec:5f:e8:eb:70/vpc-ipv4-cidr-blocks', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/network/interfaces/macs/02:ec:5f:e8:eb:70/vpc-ipv4-cidr-blocks (200, 11b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/network/interfaces/macs/02:ec:5f:e8:eb:70/subnet-id' with {'url': 'http://169.254.X.X/latest/meta-data/network/interfaces/macs/02:ec:5f:e8:eb:70/subnet-id', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/network/interfaces/macs/02:ec:5f:e8:eb:70/subnet-id (200, 24b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/network/interfaces/macs/02:ec:5f:e8:eb:70/vpc-ipv4-cidr-block' with {'url': 'http://169.254.X.X/latest/meta-data/network/interfaces/macs/02:ec:5f:e8:eb:70/vpc-ipv4-cidr-block', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/network/interfaces/macs/02:ec:5f:e8:eb:70/vpc-ipv4-cidr-block (200, 11b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/network/interfaces/macs/02:ec:5f:e8:eb:70/interface-id' with {'url': 'http://169.254.X.X/latest/meta-data/network/interfaces/macs/02:ec:5f:e8:eb:70/interface-id', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/network/interfaces/macs/02:ec:5f:e8:eb:70/interface-id (200, 21b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/network/interfaces/macs/02:ec:5f:e8:eb:70/mac' with {'url': 'http://169.254.X.X/latest/meta-data/network/interfaces/macs/02:ec:5f:e8:eb:70/mac', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/network/interfaces/macs/02:ec:5f:e8:eb:70/mac (200, 17b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/network/interfaces/macs/02:ec:5f:e8:eb:70/security-group-ids' with {'url': 'http://169.254.X.X/latest/meta-data/network/interfaces/macs/02:ec:5f:e8:eb:70/security-group-ids', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/network/interfaces/macs/02:ec:5f:e8:eb:70/security-group-ids (200, 20b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/network/interfaces/macs/02:ec:5f:e8:eb:70/local-ipv4s' with {'url': 'http://169.254.X.X/latest/meta-data/network/interfaces/macs/02:ec:5f:e8:eb:70/local-ipv4s', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/network/interfaces/macs/02:ec:5f:e8:eb:70/local-ipv4s (200, 10b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/network/interfaces/macs/02:ec:5f:e8:eb:70/owner-id' with {'url': 'http://169.254.X.X/latest/meta-data/network/interfaces/macs/02:ec:5f:e8:eb:70/owner-id', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/network/interfaces/macs/02:ec:5f:e8:eb:70/owner-id (200, 12b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/network/interfaces/macs/02:ec:5f:e8:eb:70/subnet-ipv4-cidr-block' with {'url': 'http://169.254.X.X/latest/meta-data/network/interfaces/macs/02:ec:5f:e8:eb:70/subnet-ipv4-cidr-block', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/network/interfaces/macs/02:ec:5f:e8:eb:70/subnet-ipv4-cidr-block (200, 11b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/network/interfaces/macs/02:ec:5f:e8:eb:70/device-number' with {'url': 'http://169.254.X.X/latest/meta-data/network/interfaces/macs/02:ec:5f:e8:eb:70/device-number', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/network/interfaces/macs/02:ec:5f:e8:eb:70/device-number (200, 1b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/network/interfaces/macs/02:ec:5f:e8:eb:70/vpc-id' with {'url': 'http://169.254.X.X/latest/meta-data/network/interfaces/macs/02:ec:5f:e8:eb:70/vpc-id', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/network/interfaces/macs/02:ec:5f:e8:eb:70/vpc-id (200, 21b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/placement/' with {'url': 'http://169.254.X.X/latest/meta-data/placement/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/placement/ (200, 45b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/placement/region' with {'url': 'http://169.254.X.X/latest/meta-data/placement/region', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/placement/region (200, 12b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/placement/availability-zone' with {'url': 'http://169.254.X.X/latest/meta-data/placement/availability-zone', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/placement/availability-zone (200, 13b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/placement/availability-zone-id' with {'url': 'http://169.254.X.X/latest/meta-data/placement/availability-zone-id', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/placement/availability-zone-id (200, 8b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/public-keys/' with {'url': 'http://169.254.X.X/latest/meta-data/public-keys/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/public-keys/ (200, 17b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/public-keys/0/openssh-key' with {'url': 'http://169.254.X.X/latest/meta-data/public-keys/0/openssh-key', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/public-keys/0/openssh-key (200, 397b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/services/' with {'url': 'http://169.254.X.X/latest/meta-data/services/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/services/ (200, 16b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/services/domain' with {'url': 'http://169.254.X.X/latest/meta-data/services/domain', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/services/domain (200, 13b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/services/partition' with {'url': 'http://169.254.X.X/latest/meta-data/services/partition', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/services/partition (200, 3b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/profile' with {'url': 'http://169.254.X.X/latest/meta-data/profile', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/profile (200, 11b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/local-ipv4' with {'url': 'http://169.254.X.X/latest/meta-data/local-ipv4', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/local-ipv4 (200, 10b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/reservation-id' with {'url': 'http://169.254.X.X/latest/meta-data/reservation-id', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/reservation-id (200, 19b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/local-hostname' with {'url': 'http://169.254.X.X/latest/meta-data/local-hostname', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/local-hostname (200, 43b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/security-groups' with {'url': 'http://169.254.X.X/latest/meta-data/security-groups', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/security-groups (200, 105b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/instance-life-cycle' with {'url': 'http://169.254.X.X/latest/meta-data/instance-life-cycle', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/instance-life-cycle (200, 9b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/ami-launch-index' with {'url': 'http://169.254.X.X/latest/meta-data/ami-launch-index', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/ami-launch-index (200, 1b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/hostname' with {'url': 'http://169.254.X.X/latest/meta-data/hostname', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/hostname (200, 43b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/ami-id' with {'url': 'http://169.254.X.X/latest/meta-data/ami-id', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/ami-id (200, 21b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/instance-action' with {'url': 'http://169.254.X.X/latest/meta-data/instance-action', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/instance-action (200, 4b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/mac' with {'url': 'http://169.254.X.X/latest/meta-data/mac', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/mac (200, 17b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/ami-manifest-path' with {'url': 'http://169.254.X.X/latest/meta-data/ami-manifest-path', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/ami-manifest-path (200, 9b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/instance-type' with {'url': 'http://169.254.X.X/latest/meta-data/instance-type', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/instance-type (200, 8b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/meta-data/instance-id' with {'url': 'http://169.254.X.X/latest/meta-data/instance-id', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/meta-data/instance-id (200, 19b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/dynamic/instance-identity' with {'url': 'http://169.254.X.X/latest/dynamic/instance-identity', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/dynamic/instance-identity (200, 33b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/dynamic/instance-identity/rsa2048' with {'url': 'http://169.254.X.X/latest/dynamic/instance-identity/rsa2048', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/dynamic/instance-identity/rsa2048 (200, 1438b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/dynamic/instance-identity/document' with {'url': 'http://169.254.X.X/latest/dynamic/instance-identity/document', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/dynamic/instance-identity/document (200, 480b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/dynamic/instance-identity/pkcs7' with {'url': 'http://169.254.X.X/latest/dynamic/instance-identity/pkcs7', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/dynamic/instance-identity/pkcs7 (200, 1122b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.X.X/latest/dynamic/instance-identity/signature' with {'url': 'http://169.254.X.X/latest/dynamic/instance-identity/signature', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Dec 07 05:10:04 cloud-init[2442]: url_helper.py[DEBUG]: Read from http://169.254.X.X/latest/dynamic/instance-identity/signature (200, 174b) after 1 attempts
Dec 07 05:10:04 cloud-init[2442]: DataSourceEc2.py[DEBUG]: Crawl of metadata service took 0 seconds
Dec 07 05:10:04 cloud-init[2442]: stages.py[INFO]: Loaded datasource DataSourceEc2 - DataSourceEc2
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Reading from /proc/cmdline (quiet=False)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Read 82 bytes from /proc/cmdline
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Read 559 bytes from /etc/cloud/cloud.cfg
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Attempting to load yaml from string of length 559 with allowed root types (<type 'dict'>,)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg (quiet=False)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Read 586 bytes from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Attempting to load yaml from string of length 586 with allowed root types (<type 'dict'>,)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Read 1963 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Attempting to load yaml from string of length 1963 with allowed root types (<type 'dict'>,)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/00_defaults.cfg (quiet=False)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Read 2610 bytes from /etc/cloud/cloud.cfg.d/00_defaults.cfg
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Attempting to load yaml from string of length 2610 with allowed root types (<type 'dict'>,)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/i-0cf2510c3fab4XXXX'
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Reading from /var/lib/cloud/instances/i-0cf2510c3fab4XXXX/datasource (quiet=False)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cf2510c3fab4XXXX/datasource - wb: [644] 29 bytes
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 29 bytes
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 20 bytes
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 20 bytes
Dec 07 05:10:04 cloud-init[2442]: cloud-init[DEBUG]: init will now be targeting instance id: i-0cf2510c3fab4XXXX
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Reading from /proc/cmdline (quiet=False)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Read 82 bytes from /proc/cmdline
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Read 559 bytes from /etc/cloud/cloud.cfg
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Attempting to load yaml from string of length 559 with allowed root types (<type 'dict'>,)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg (quiet=False)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Read 586 bytes from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Attempting to load yaml from string of length 586 with allowed root types (<type 'dict'>,)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Read 1963 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Attempting to load yaml from string of length 1963 with allowed root types (<type 'dict'>,)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/00_defaults.cfg (quiet=False)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Read 2610 bytes from /etc/cloud/cloud.cfg.d/00_defaults.cfg
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Attempting to load yaml from string of length 2610 with allowed root types (<type 'dict'>,)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 9480 bytes
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cf2510c3fab4XXXX/user-data.txt - wb: [600] 397 bytes
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cf2510c3fab4XXXX/user-data.txt.i - wb: [600] 740 bytes
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cf2510c3fab4XXXX/vendor-data.txt - wb: [600] 4 bytes
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cf2510c3fab4XXXX/vendor-data.txt.i - wb: [600] 345 bytes
Dec 07 05:10:04 cloud-init[2442]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/consume_data - wb: [644] 20 bytes
Dec 07 05:10:04 cloud-init[2442]: helpers.py[DEBUG]: Running consume_data using lock (<FileLock using file '/var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/consume_data'>)
Dec 07 05:10:04 cloud-init[2442]: launch_index.py[DEBUG]: Discarding 0 multipart messages which do not match launch index 0
Dec 07 05:10:04 cloud-init[2442]: stages.py[DEBUG]: Added default handler for set(['text/cloud-config-jsonp', 'text/cloud-config']) from CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']]
Dec 07 05:10:04 cloud-init[2442]: stages.py[DEBUG]: Added default handler for set(['text/x-shellscript']) from ShellScriptPartHandler: [['text/x-shellscript']]
Dec 07 05:10:04 cloud-init[2442]: stages.py[DEBUG]: Added default handler for set(['text/cloud-boothook']) from BootHookPartHandler: [['text/cloud-boothook']]
Dec 07 05:10:04 cloud-init[2442]: stages.py[DEBUG]: Added default handler for set(['text/upstart-job']) from UpstartJobPartHandler: [['text/upstart-job']]
Dec 07 05:10:04 cloud-init[2442]: __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__begin__, None, 2) with frequency once-per-instance
Dec 07 05:10:04 cloud-init[2442]: __init__.py[DEBUG]: Calling handler UpstartJobPartHandler: [['text/upstart-job']] (__begin__, None, 2) with frequency once-per-instance
Dec 07 05:10:04 cloud-init[2442]: __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__begin__, None, 3) with frequency once-per-instance
Dec 07 05:10:04 cloud-init[2442]: __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__begin__, None, 2) with frequency once-per-instance
Dec 07 05:10:04 cloud-init[2442]: __init__.py[DEBUG]: {'Content-Type': 'text/x-shellscript', 'Content-Disposition': 'attachment; filename="part-001"', 'MIME-Version': '1.0'}
Dec 07 05:10:04 cloud-init[2442]: __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (text/x-shellscript, part-001, 2) with frequency once-per-instance
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Writing to /var/lib/cloud/instance/scripts/part-001 - wb: [700] 397 bytes
Dec 07 05:10:04 cloud-init[2442]: __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__end__, None, 2) with frequency once-per-instance
Dec 07 05:10:04 cloud-init[2442]: __init__.py[DEBUG]: Calling handler UpstartJobPartHandler: [['text/upstart-job']] (__end__, None, 2) with frequency once-per-instance
Dec 07 05:10:04 cloud-init[2442]: __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__end__, None, 3) with frequency once-per-instance
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cf2510c3fab4XXXX/cloud-config.txt - wb: [600] 0 bytes
Dec 07 05:10:04 cloud-init[2442]: __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__end__, None, 2) with frequency once-per-instance
Dec 07 05:10:04 cloud-init[2442]: stages.py[DEBUG]: no vendordata from datasource
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Reading from /proc/cmdline (quiet=False)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Read 82 bytes from /proc/cmdline
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Read 559 bytes from /etc/cloud/cloud.cfg
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Attempting to load yaml from string of length 559 with allowed root types (<type 'dict'>,)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg (quiet=False)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Read 586 bytes from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Attempting to load yaml from string of length 586 with allowed root types (<type 'dict'>,)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Read 1963 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Attempting to load yaml from string of length 1963 with allowed root types (<type 'dict'>,)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/00_defaults.cfg (quiet=False)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Read 2610 bytes from /etc/cloud/cloud.cfg.d/00_defaults.cfg
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Attempting to load yaml from string of length 2610 with allowed root types (<type 'dict'>,)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Read 0 bytes from /var/lib/cloud/instance/cloud-config.txt
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<type 'dict'>,)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: load_yaml given empty string, returning default
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Read 0 bytes from /var/lib/cloud/instance/cloud-config.txt
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<type 'dict'>,)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: load_yaml given empty string, returning default
Dec 07 05:10:04 cloud-init[2442]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Dec 07 05:10:04 cloud-init[2442]: stages.py[INFO]: Skipping modules ['resolv-conf'] because they are not verified on distro 'amazon'.  To run anyway, add them to 'unverified_modules' in config.
Dec 07 05:10:04 cloud-init[2442]: stages.py[DEBUG]: Running module migrator (<module 'cloudinit.config.cc_migrator' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_migrator.pyc'>) with frequency always
Dec 07 05:10:04 cloud-init[2442]: helpers.py[DEBUG]: Running config-migrator using lock (<cloudinit.helpers.DummyLock object at 0x7f2145a76150>)
Dec 07 05:10:04 cloud-init[2442]: cc_migrator.py[DEBUG]: Migrating semaphores which are not named canonically.
Dec 07 05:10:04 cloud-init[2442]: cc_migrator.py[DEBUG]: Looking at consume_data
Dec 07 05:10:04 cloud-init[2442]: cc_migrator.py[DEBUG]: Searching for legacy per-instance semaphores under /var/lib/cloud/sem
Dec 07 05:10:04 cloud-init[2442]: cc_migrator.py[DEBUG]: Migrating semaphores which have been renamed or split.
Dec 07 05:10:04 cloud-init[2442]: cc_migrator.py[DEBUG]: Looking in /var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem
Dec 07 05:10:04 cloud-init[2442]: cc_migrator.py[DEBUG]: Looking in /var/lib/cloud/sem
Dec 07 05:10:04 cloud-init[2442]: stages.py[DEBUG]: Running module rsyslog (<module 'cloudinit.config.cc_rsyslog' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_rsyslog.pyc'>) with frequency once-per-instance
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_rsyslog - wb: [644] 20 bytes
Dec 07 05:10:04 cloud-init[2442]: helpers.py[DEBUG]: Running config-rsyslog using lock (<FileLock using file '/var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_rsyslog'>)
Dec 07 05:10:04 cloud-init[2442]: cc_rsyslog.py[DEBUG]: Skipping module named rsyslog, no 'rsyslog' key in configuration
Dec 07 05:10:04 cloud-init[2442]: stages.py[DEBUG]: Running module bootcmd (<module 'cloudinit.config.cc_bootcmd' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_bootcmd.pyc'>) with frequency always
Dec 07 05:10:04 cloud-init[2442]: helpers.py[DEBUG]: Running config-bootcmd using lock (<cloudinit.helpers.DummyLock object at 0x7f2145d6f210>)
Dec 07 05:10:04 cloud-init[2442]: cc_bootcmd.py[DEBUG]: Skipping module named bootcmd, no 'bootcmd' key in configuration
Dec 07 05:10:04 cloud-init[2442]: stages.py[DEBUG]: Running module write-files (<module 'cloudinit.config.cc_write_files' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_write_files.pyc'>) with frequency once-per-instance
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_write_files - wb: [644] 20 bytes
Dec 07 05:10:04 cloud-init[2442]: helpers.py[DEBUG]: Running config-write-files using lock (<FileLock using file '/var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_write_files'>)
Dec 07 05:10:04 cloud-init[2442]: cc_write_files.py[DEBUG]: Skipping module named write-files, no/empty 'write_files' key in configuration
Dec 07 05:10:04 cloud-init[2442]: stages.py[DEBUG]: Running module write-metadata (<module 'cloudinit.config.cc_write_metadata' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_write_metadata.pyc'>) with frequency once-per-instance
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_write_metadata - wb: [644] 20 bytes
Dec 07 05:10:04 cloud-init[2442]: helpers.py[DEBUG]: Running config-write-metadata using lock (<FileLock using file '/var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_write_metadata'>)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Writing to /etc/yum/vars/awsregion - wb: [644] 12 bytes
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Changing the ownership of /etc/yum/vars/awsregion to 0:0
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Writing to /etc/yum/vars/awsdomain - wb: [644] 13 bytes
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Changing the ownership of /etc/yum/vars/awsdomain to 0:0
Dec 07 05:10:04 cloud-init[2442]: stages.py[DEBUG]: Running module growpart (<module 'cloudinit.config.cc_growpart' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_growpart.pyc'>) with frequency always
Dec 07 05:10:04 cloud-init[2442]: helpers.py[DEBUG]: Running config-growpart using lock (<cloudinit.helpers.DummyLock object at 0x7f2145d6f390>)
Dec 07 05:10:04 cloud-init[2442]: cc_growpart.py[DEBUG]: No 'growpart' entry in cfg.  Using default: {'ignore_growroot_disabled': False, 'mode': 'auto', 'devices': ['/']}
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Running command ['growpart', '--help'] with allowed return codes [0] (shell=False, capture=True)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Reading from /proc/2442/mountinfo (quiet=False)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Read 528 bytes from /proc/2442/mountinfo
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Reading from /sys/class/block/xvda1/partition (quiet=False)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Read 2 bytes from /sys/class/block/xvda1/partition
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Reading from /sys/devices/vbd-51712/block/xvda/dev (quiet=False)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Read 6 bytes from /sys/devices/vbd-51712/block/xvda/dev
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Running command ['growpart', '--dry-run', '/dev/xvda', '1'] with allowed return codes [0] (shell=False, capture=True)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: resize_devices took 0.032 seconds
Dec 07 05:10:04 cloud-init[2442]: cc_growpart.py[DEBUG]: '/' NOCHANGE: no change necessary (/dev/xvda, 1)
Dec 07 05:10:04 cloud-init[2442]: stages.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_resizefs.pyc'>) with frequency always
Dec 07 05:10:04 cloud-init[2442]: helpers.py[DEBUG]: Running config-resizefs using lock (<cloudinit.helpers.DummyLock object at 0x7f2145d6f210>)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Reading from /proc/2442/mountinfo (quiet=False)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Read 528 bytes from /proc/2442/mountinfo
Dec 07 05:10:04 cloud-init[2442]: cc_resizefs.py[DEBUG]: resize_info: dev=/dev/xvda1 mnt_point=/ path=/
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Read 53 bytes from /proc/1/environ
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Read 1302 bytes from /proc/self/status
Dec 07 05:10:04 cloud-init[2442]: cc_resizefs.py[DEBUG]: Resizing / (ext4) using resize2fs /dev/xvda1
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Forked child 2484 who will run callback log_time
Dec 07 05:10:04 cloud-init[2442]: cc_resizefs.py[DEBUG]: Resizing (via forking) root filesystem (type=ext4, val=noblock)
Dec 07 05:10:04 cloud-init[2442]: stages.py[DEBUG]: Running module set-hostname (<module 'cloudinit.config.cc_set_hostname' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_set_hostname.pyc'>) with frequency once-per-instance
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_set_hostname - wb: [644] 20 bytes
Dec 07 05:10:04 cloud-init[2442]: helpers.py[DEBUG]: Running config-set-hostname using lock (<FileLock using file '/var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_set_hostname'>)
Dec 07 05:10:04 cloud-init[2442]: cc_set_hostname.py[DEBUG]: Configuration option 'preserve_hostname' is set, not setting the hostname in module set-hostname
Dec 07 05:10:04 cloud-init[2442]: stages.py[DEBUG]: Running module update-hostname (<module 'cloudinit.config.cc_update_hostname' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_update_hostname.pyc'>) with frequency always
Dec 07 05:10:04 cloud-init[2442]: helpers.py[DEBUG]: Running config-update-hostname using lock (<cloudinit.helpers.DummyLock object at 0x7f2145a5cfd0>)
Dec 07 05:10:04 cloud-init[2442]: cc_update_hostname.py[DEBUG]: Configuration option 'preserve_hostname' is set, not updating the hostname in module update-hostname
Dec 07 05:10:04 cloud-init[2442]: stages.py[DEBUG]: Running module update-etc-hosts (<module 'cloudinit.config.cc_update_etc_hosts' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_update_etc_hosts.pyc'>) with frequency always
Dec 07 05:10:04 cloud-init[2442]: helpers.py[DEBUG]: Running config-update-etc-hosts using lock (<cloudinit.helpers.DummyLock object at 0x7f2145a5cf10>)
Dec 07 05:10:04 cloud-init[2442]: cc_update_etc_hosts.py[DEBUG]: Configuration option 'manage_etc_hosts' is not set, not managing /etc/hosts in module update-etc-hosts
Dec 07 05:10:04 cloud-init[2442]: stages.py[DEBUG]: Running module resolv-conf (<module 'cloudinit.config.cc_resolv_conf' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_resolv_conf.pyc'>) with frequency once-per-instance
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_resolv_conf - wb: [644] 20 bytes
Dec 07 05:10:04 cloud-init[2442]: helpers.py[DEBUG]: Running config-resolv-conf using lock (<FileLock using file '/var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_resolv_conf'>)
Dec 07 05:10:04 cloud-init[2442]: cc_resolv_conf.py[DEBUG]: Skipping module named resolv-conf, no 'manage_resolv_conf' key in configuration
Dec 07 05:10:04 cloud-init[2442]: stages.py[DEBUG]: Running module users-groups (<module 'cloudinit.config.cc_users_groups' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_users_groups.pyc'>) with frequency once-per-instance
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_users_groups - wb: [644] 20 bytes
Dec 07 05:10:04 cloud-init[2484]: util.py[DEBUG]: Running command ('resize2fs', '/dev/xvda1') with allowed return codes [0] (shell=False, capture=True)
Dec 07 05:10:04 cloud-init[2442]: helpers.py[DEBUG]: Running config-users-groups using lock (<FileLock using file '/var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_users_groups'>)
Dec 07 05:10:04 cloud-init[2442]: __init__.py[DEBUG]: Adding user ec2-user
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Running hidden command to protect sensitive input/output logstring: ['useradd', 'ec2-user', '--shell', '/bin/bash', '--comment', 'EC2 Default User', '--groups', 'wheel', '-m']
Dec 07 05:10:04 cloud-init[2484]: util.py[DEBUG]: backgrounded Resizing took 0.005 seconds
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Running command ['usermod', '-L', 'ec2-user'] with allowed return codes [0] (shell=False, capture=True)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Reading from /etc/sudoers (quiet=False)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Read 3729 bytes from /etc/sudoers
Dec 07 05:10:04 cloud-init[2442]: stages.py[DEBUG]: Running module ssh (<module 'cloudinit.config.cc_ssh' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_ssh.pyc'>) with frequency once-per-instance
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_ssh - wb: [644] 20 bytes
Dec 07 05:10:04 cloud-init[2442]: helpers.py[DEBUG]: Running config-ssh using lock (<FileLock using file '/var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_ssh'>)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Running command ['ssh-keygen', '-t', 'rsa', '-N', '', '-f', '/etc/ssh/ssh_host_rsa_key'] with allowed return codes [0] (shell=False, capture=False)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Running command ['ssh-keygen', '-t', 'dsa', '-N', '', '-f', '/etc/ssh/ssh_host_dsa_key'] with allowed return codes [0] (shell=False, capture=False)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ecdsa', '-N', '', '-f', '/etc/ssh/ssh_host_ecdsa_key'] with allowed return codes [0] (shell=False, capture=False)
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh to 500:500
Dec 07 05:10:04 cloud-init[2442]: util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
Dec 07 05:10:05 cloud-init[2442]: util.py[DEBUG]: Read 3936 bytes from /etc/ssh/sshd_config
Dec 07 05:10:05 cloud-init[2442]: util.py[DEBUG]: Writing to /home/ec2-user/.ssh/authorized_keys - wb: [600] 397 bytes
Dec 07 05:10:05 cloud-init[2442]: util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh/authorized_keys to 500:500
Dec 07 05:10:05 cloud-init[2442]: util.py[DEBUG]: Changing the ownership of /root/.ssh to 0:0
Dec 07 05:10:05 cloud-init[2442]: util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
Dec 07 05:10:05 cloud-init[2442]: util.py[DEBUG]: Read 3936 bytes from /etc/ssh/sshd_config
Dec 07 05:10:05 cloud-init[2442]: util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 554 bytes
Dec 07 05:10:05 cloud-init[2442]: util.py[DEBUG]: Changing the ownership of /root/.ssh/authorized_keys to 0:0
Dec 07 05:10:05 cloud-init[2442]: cloud-init[DEBUG]: Ran 13 modules with 0 failures
Dec 07 05:10:05 cloud-init[2442]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
Dec 07 05:10:05 cloud-init[2442]: util.py[DEBUG]: Read 10 bytes from /proc/uptime
Dec 07 05:10:05 cloud-init[2442]: util.py[DEBUG]: cloud-init mode 'init' took 0.696 seconds (0.70)
Dec 07 05:10:05 cloud-init[2508]: util.py[DEBUG]: Cloud-init v. 0.7.6 running 'modules:config' at Mon, 07 Dec 2020 05:10:05 +0000. Up 7.07 seconds.
Dec 07 05:10:05 cloud-init[2508]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Dec 07 05:10:05 cloud-init[2508]: stages.py[DEBUG]: Running module mounts (<module 'cloudinit.config.cc_mounts' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_mounts.pyc'>) with frequency once-per-instance
Dec 07 05:10:05 cloud-init[2508]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_mounts - wb: [644] 20 bytes
Dec 07 05:10:05 cloud-init[2508]: helpers.py[DEBUG]: Running config-mounts using lock (<FileLock using file '/var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_mounts'>)
Dec 07 05:10:05 cloud-init[2508]: cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
Dec 07 05:10:05 cloud-init[2508]: DataSourceEc2.py[DEBUG]: Unable to convert ephemeral0 to a device
Dec 07 05:10:05 cloud-init[2508]: cc_mounts.py[DEBUG]: Ignoring nonexistent named mount ephemeral0
Dec 07 05:10:05 cloud-init[2508]: cc_mounts.py[DEBUG]: changed ephemeral0 => None
Dec 07 05:10:05 cloud-init[2508]: cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
Dec 07 05:10:05 cloud-init[2508]: DataSourceEc2.py[DEBUG]: Unable to convert swap to a device
Dec 07 05:10:05 cloud-init[2508]: cc_mounts.py[DEBUG]: Ignoring nonexistent named mount swap
Dec 07 05:10:05 cloud-init[2508]: cc_mounts.py[DEBUG]: changed swap => None
Dec 07 05:10:05 cloud-init[2508]: cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
Dec 07 05:10:05 cloud-init[2508]: DataSourceEc2.py[DEBUG]: Unable to convert ephemeral0 to a device
Dec 07 05:10:05 cloud-init[2508]: cc_mounts.py[DEBUG]: Ignoring nonexistant default named mount ephemeral0
Dec 07 05:10:05 cloud-init[2508]: cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
Dec 07 05:10:05 cloud-init[2508]: DataSourceEc2.py[DEBUG]: Unable to convert swap to a device
Dec 07 05:10:05 cloud-init[2508]: cc_mounts.py[DEBUG]: Ignoring nonexistant default named mount swap
Dec 07 05:10:05 cloud-init[2508]: cc_mounts.py[DEBUG]: Skipping non-existent device named None
Dec 07 05:10:05 cloud-init[2508]: cc_mounts.py[DEBUG]: Skipping non-existent device named None
Dec 07 05:10:05 cloud-init[2508]: cc_mounts.py[DEBUG]: no need to setup swap
Dec 07 05:10:05 cloud-init[2508]: cc_mounts.py[DEBUG]: No modifications to fstab needed.
Dec 07 05:10:05 cloud-init[2508]: stages.py[DEBUG]: Running module locale (<module 'cloudinit.config.cc_locale' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_locale.pyc'>) with frequency once-per-instance
Dec 07 05:10:05 cloud-init[2508]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_locale - wb: [644] 20 bytes
Dec 07 05:10:05 cloud-init[2508]: helpers.py[DEBUG]: Running config-locale using lock (<FileLock using file '/var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_locale'>)
Dec 07 05:10:05 cloud-init[2508]: cc_locale.py[DEBUG]: Setting locale to en_US.UTF-8
Dec 07 05:10:05 cloud-init[2508]: util.py[DEBUG]: Reading from /etc/sysconfig/i18n (quiet=False)
Dec 07 05:10:05 cloud-init[2508]: util.py[DEBUG]: Read 19 bytes from /etc/sysconfig/i18n
Dec 07 05:10:05 cloud-init[2508]: util.py[DEBUG]: Writing to /etc/sysconfig/i18n - wb: [644] 17 bytes
Dec 07 05:10:05 cloud-init[2508]: stages.py[DEBUG]: Running module set-passwords (<module 'cloudinit.config.cc_set_passwords' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_set_passwords.pyc'>) with frequency once-per-instance
Dec 07 05:10:05 cloud-init[2508]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_set_passwords - wb: [644] 20 bytes
Dec 07 05:10:05 cloud-init[2508]: helpers.py[DEBUG]: Running config-set-passwords using lock (<FileLock using file '/var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_set_passwords'>)
Dec 07 05:10:05 cloud-init[2508]: util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
Dec 07 05:10:05 cloud-init[2508]: util.py[DEBUG]: Read 3936 bytes from /etc/ssh/sshd_config
Dec 07 05:10:05 cloud-init[2508]: cc_set_passwords.py[DEBUG]: Replacing auth line 65 with no
Dec 07 05:10:05 cloud-init[2508]: util.py[DEBUG]: Writing to /etc/ssh/sshd_config - wb: [644] 3935 bytes
Dec 07 05:10:05 cloud-init[2508]: util.py[DEBUG]: Running command ['service', 'sshd', 'status'] with allowed return codes [0] (shell=False, capture=True)
Dec 07 05:10:05 cloud-init[2508]: stages.py[DEBUG]: Running module yum-configure (<module 'cloudinit.config.cc_yum_configure' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_yum_configure.pyc'>) with frequency once-per-instance
Dec 07 05:10:05 cloud-init[2508]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_yum_configure - wb: [644] 20 bytes
Dec 07 05:10:05 cloud-init[2508]: helpers.py[DEBUG]: Running config-yum-configure using lock (<FileLock using file '/var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_yum_configure'>)
Dec 07 05:10:05 cloud-init[2508]: cc_yum_configure.py[DEBUG]: Generating default repo files
Dec 07 05:10:05 cloud-init[2508]: __init__.py[DEBUG]: filtered distro mirror info: {'regional': u'repo.eu-central-1.amazonaws.com'}
Dec 07 05:10:05 cloud-init[2508]: cc_yum_configure.py[DEBUG]: Using mirror: repo.eu-central-1.amazonaws.com
Dec 07 05:10:05 cloud-init[2508]: cc_yum_configure.py[INFO]: No releasever provided, leaving yum.conf unchanged.
Dec 07 05:10:05 cloud-init[2508]: stages.py[DEBUG]: Running module yum-add-repo (<module 'cloudinit.config.cc_yum_add_repo' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_yum_add_repo.pyc'>) with frequency once-per-instance
Dec 07 05:10:05 cloud-init[2508]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_yum_add_repo - wb: [644] 20 bytes
Dec 07 05:10:05 cloud-init[2508]: helpers.py[DEBUG]: Running config-yum-add-repo using lock (<FileLock using file '/var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_yum_add_repo'>)
Dec 07 05:10:05 cloud-init[2508]: cc_yum_add_repo.py[DEBUG]: Skipping module named yum-add-repo, no 'yum_repos' configuration found
Dec 07 05:10:05 cloud-init[2508]: stages.py[DEBUG]: Running module package-update-upgrade-install (<module 'cloudinit.config.cc_package_update_upgrade_install' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_package_update_upgrade_install.pyc'>) with frequency once-per-instance
Dec 07 05:10:05 cloud-init[2508]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_package_update_upgrade_install - wb: [644] 20 bytes
Dec 07 05:10:05 cloud-init[2508]: helpers.py[DEBUG]: Running config-package-update-upgrade-install using lock (<FileLock using file '/var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_package_update_upgrade_install'>)
Dec 07 05:10:05 cloud-init[2508]: amazon.py[DEBUG]: Upgrade level: security
Dec 07 05:10:05 cloud-init[2508]: util.py[DEBUG]: Running command ['yum', '-t', '-y', '--exclude=kernel', '--exclude=nvidia*', '--exclude=cudatoolkit', '--security', '--sec-severity=critical', '--sec-severity=important', 'upgrade'] with allowed return codes [0] (shell=False, capture=False)
Dec 07 05:10:16 cloud-init[2508]: stages.py[DEBUG]: Running module timezone (<module 'cloudinit.config.cc_timezone' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_timezone.pyc'>) with frequency once-per-instance
Dec 07 05:10:16 cloud-init[2508]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_timezone - wb: [644] 20 bytes
Dec 07 05:10:16 cloud-init[2508]: helpers.py[DEBUG]: Running config-timezone using lock (<FileLock using file '/var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_timezone'>)
Dec 07 05:10:16 cloud-init[2508]: cc_timezone.py[DEBUG]: Skipping module named timezone, no 'timezone' specified
Dec 07 05:10:16 cloud-init[2508]: stages.py[DEBUG]: Running module puppet (<module 'cloudinit.config.cc_puppet' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_puppet.pyc'>) with frequency once-per-instance
Dec 07 05:10:16 cloud-init[2508]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_puppet - wb: [644] 20 bytes
Dec 07 05:10:16 cloud-init[2508]: helpers.py[DEBUG]: Running config-puppet using lock (<FileLock using file '/var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_puppet'>)
Dec 07 05:10:16 cloud-init[2508]: cc_puppet.py[DEBUG]: Skipping module named puppet, no 'puppet' configuration found
Dec 07 05:10:16 cloud-init[2508]: stages.py[DEBUG]: Running module disable-ec2-metadata (<module 'cloudinit.config.cc_disable_ec2_metadata' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_disable_ec2_metadata.pyc'>) with frequency always
Dec 07 05:10:16 cloud-init[2508]: helpers.py[DEBUG]: Running config-disable-ec2-metadata using lock (<cloudinit.helpers.DummyLock object at 0x7f00080b2690>)
Dec 07 05:10:16 cloud-init[2508]: cc_disable_ec2_metadata.py[DEBUG]: Skipping module named disable-ec2-metadata, disabling the ec2 route not enabled
Dec 07 05:10:16 cloud-init[2508]: stages.py[DEBUG]: Running module runcmd (<module 'cloudinit.config.cc_runcmd' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_runcmd.pyc'>) with frequency once-per-instance
Dec 07 05:10:16 cloud-init[2508]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_runcmd - wb: [644] 20 bytes
Dec 07 05:10:16 cloud-init[2508]: helpers.py[DEBUG]: Running config-runcmd using lock (<FileLock using file '/var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_runcmd'>)
Dec 07 05:10:16 cloud-init[2508]: cc_runcmd.py[DEBUG]: Skipping module named runcmd, no 'runcmd' key in configuration
Dec 07 05:10:16 cloud-init[2508]: cloud-init[DEBUG]: Ran 10 modules with 0 failures
Dec 07 05:10:16 cloud-init[2508]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
Dec 07 05:10:16 cloud-init[2508]: util.py[DEBUG]: Read 11 bytes from /proc/uptime
Dec 07 05:10:16 cloud-init[2508]: util.py[DEBUG]: cloud-init mode 'modules' took 11.697 seconds (11.70)
Dec 07 05:10:18 cloud-init[2851]: util.py[DEBUG]: Cloud-init v. 0.7.6 running 'modules:final' at Mon, 07 Dec 2020 05:10:17 +0000. Up 19.89 seconds.
Dec 07 05:10:18 cloud-init[2851]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Dec 07 05:10:18 cloud-init[2851]: stages.py[DEBUG]: Running module scripts-per-once (<module 'cloudinit.config.cc_scripts_per_once' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_scripts_per_once.pyc'>) with frequency once
Dec 07 05:10:18 cloud-init[2851]: util.py[DEBUG]: Writing to /var/lib/cloud/sem/config_scripts_per_once.once - wb: [644] 20 bytes
Dec 07 05:10:18 cloud-init[2851]: helpers.py[DEBUG]: Running config-scripts-per-once using lock (<FileLock using file '/var/lib/cloud/sem/config_scripts_per_once.once'>)
Dec 07 05:10:18 cloud-init[2851]: stages.py[DEBUG]: Running module scripts-per-boot (<module 'cloudinit.config.cc_scripts_per_boot' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_scripts_per_boot.pyc'>) with frequency always
Dec 07 05:10:18 cloud-init[2851]: helpers.py[DEBUG]: Running config-scripts-per-boot using lock (<cloudinit.helpers.DummyLock object at 0x7f3bfd8656d0>)
Dec 07 05:10:18 cloud-init[2851]: stages.py[DEBUG]: Running module scripts-per-instance (<module 'cloudinit.config.cc_scripts_per_instance' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_scripts_per_instance.pyc'>) with frequency once-per-instance
Dec 07 05:10:18 cloud-init[2851]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_scripts_per_instance - wb: [644] 20 bytes
Dec 07 05:10:18 cloud-init[2851]: helpers.py[DEBUG]: Running config-scripts-per-instance using lock (<FileLock using file '/var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_scripts_per_instance'>)
Dec 07 05:10:18 cloud-init[2851]: stages.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_scripts_user.pyc'>) with frequency once-per-instance
Dec 07 05:10:18 cloud-init[2851]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_scripts_user - wb: [644] 20 bytes
Dec 07 05:10:18 cloud-init[2851]: helpers.py[DEBUG]: Running config-scripts-user using lock (<FileLock using file '/var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_scripts_user'>)
Dec 07 05:10:18 cloud-init[2851]: util.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/part-001'] with allowed return codes [0] (shell=True, capture=False)
Dec 07 05:12:16 cloud-init[2851]: stages.py[DEBUG]: Running module ssh-authkey-fingerprints (<module 'cloudinit.config.cc_ssh_authkey_fingerprints' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_ssh_authkey_fingerprints.pyc'>) with frequency once-per-instance
Dec 07 05:12:16 cloud-init[2851]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_ssh_authkey_fingerprints - wb: [644] 20 bytes
Dec 07 05:12:16 cloud-init[2851]: helpers.py[DEBUG]: Running config-ssh-authkey-fingerprints using lock (<FileLock using file '/var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_ssh_authkey_fingerprints'>)
Dec 07 05:12:16 cloud-init[2851]: util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
Dec 07 05:12:16 cloud-init[2851]: util.py[DEBUG]: Read 3935 bytes from /etc/ssh/sshd_config
Dec 07 05:12:16 cloud-init[2851]: util.py[DEBUG]: Reading from /home/ec2-user/.ssh/authorized_keys (quiet=False)
Dec 07 05:12:16 cloud-init[2851]: util.py[DEBUG]: Read 397 bytes from /home/ec2-user/.ssh/authorized_keys
Dec 07 05:12:16 cloud-init[2851]: stages.py[DEBUG]: Running module keys-to-console (<module 'cloudinit.config.cc_keys_to_console' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_keys_to_console.pyc'>) with frequency once-per-instance
Dec 07 05:12:16 cloud-init[2851]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_keys_to_console - wb: [644] 19 bytes
Dec 07 05:12:16 cloud-init[2851]: helpers.py[DEBUG]: Running config-keys-to-console using lock (<FileLock using file '/var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_keys_to_console'>)
Dec 07 05:12:16 cloud-init[2851]: util.py[DEBUG]: Running command ['/usr/libexec/cloud-init/write-ssh-key-fingerprints', '', 'ssh-dss'] with allowed return codes [0] (shell=False, capture=True)
Dec 07 05:12:16 cloud-init[2851]: stages.py[DEBUG]: Running module phone-home (<module 'cloudinit.config.cc_phone_home' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_phone_home.pyc'>) with frequency once-per-instance
Dec 07 05:12:16 cloud-init[2851]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_phone_home - wb: [644] 20 bytes
Dec 07 05:12:16 cloud-init[2851]: helpers.py[DEBUG]: Running config-phone-home using lock (<FileLock using file '/var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_phone_home'>)
Dec 07 05:12:16 cloud-init[2851]: cc_phone_home.py[DEBUG]: Skipping module named phone-home, no 'phone_home' configuration found
Dec 07 05:12:16 cloud-init[2851]: stages.py[DEBUG]: Running module final-message (<module 'cloudinit.config.cc_final_message' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_final_message.pyc'>) with frequency always
Dec 07 05:12:16 cloud-init[2851]: helpers.py[DEBUG]: Running config-final-message using lock (<cloudinit.helpers.DummyLock object at 0x7f3bfd5028d0>)
Dec 07 05:12:16 cloud-init[2851]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
Dec 07 05:12:16 cloud-init[2851]: util.py[DEBUG]: Read 13 bytes from /proc/uptime
Dec 07 05:12:16 cloud-init[2851]: util.py[DEBUG]: Cloud-init v. 0.7.6 finished at Mon, 07 Dec 2020 05:12:16 +0000. Datasource DataSourceEc2.  Up 139.07 seconds
Dec 07 05:12:16 cloud-init[2851]: util.py[DEBUG]: Writing to /var/lib/cloud/instance/boot-finished - wb: [644] 52 bytes
Dec 07 05:12:16 cloud-init[2851]: stages.py[DEBUG]: Running module power-state-change (<module 'cloudinit.config.cc_power_state_change' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_power_state_change.pyc'>) with frequency once-per-instance
Dec 07 05:12:16 cloud-init[2851]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_power_state_change - wb: [644] 19 bytes
Dec 07 05:12:16 cloud-init[2851]: helpers.py[DEBUG]: Running config-power-state-change using lock (<FileLock using file '/var/lib/cloud/instances/i-0cf2510c3fab4XXXX/sem/config_power_state_change'>)
Dec 07 05:12:16 cloud-init[2851]: cc_power_state_change.py[DEBUG]: no power_state provided. doing nothing
Dec 07 05:12:16 cloud-init[2851]: cloud-init[DEBUG]: Ran 9 modules with 0 failures
Dec 07 05:12:16 cloud-init[2851]: util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
Dec 07 05:12:16 cloud-init[2851]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
Dec 07 05:12:16 cloud-init[2851]: util.py[DEBUG]: Read 13 bytes from /proc/uptime
Dec 07 05:12:16 cloud-init[2851]: util.py[DEBUG]: cloud-init mode 'modules' took 118.736 seconds (119.19)
